import type { Metadata } from "next";
import { Container } from "@/components/Container";
import { Header } from "@/components/Header";

import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "The blog - Este é um blog com Next.js",
    template: "%s | The blog",
  },
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="pt-BR">
      <body>
        <Container>
          <Header />

          {children}

          <footer>
            <h1 className="text-6xl font-bold text-center py-8">Footer</h1>
          </footer>
        </Container>
      </body>
    </html>
  );
}
